### ISSUE TITLE
ClassDefNotFound when using "retrieve" when using "Protocol Message Store" and not querying history

### ISSUE THREAD

**Issue by jre-1986** [GIP-SmartMercial/xyna-factory#202]
The following service returns a "ClassDefNotFound" when using "retrieve" with the "use history"-boolean turned to false:
"xfmg.xfmon.protocolmsg.ProtocolMessageStore" from the Application "Connection", Version 1.0.12.

Error message:
`com.gip.xyna.xprc.xprcods.orderarchive.XynaExceptionInformationThrowable: com.gip.xyna.xprc.exceptions.XPRC_UNEXPECTED_ERROR_PROCESS: unexpected error executing order jre.Xyna9TestProtocolRetrieve: NoClassDefFoundError xfmg/xfmon/protocolmsg/data/ProtocolMessageStorable`

Might be related to the issue with querying XynaClusterPersistenceLayers.

**Comment by corneliuslippert-gip** [comment]
I had a similar problem when using SSH access with hostkeyrepository/identityrepository configured on MemoryPersistenceLayer:

`java.lang.ClassNotFoundException xact.ssh.HostKeyStorable. (depth: 2)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.gip.xyna.xnwh.persistence.memory.gen.i5.Thostkeyrepository25.conditionBoolean0(Thostkeyrepository25.java:83)
	at com.gip.xyna.xnwh.persistence.memory.gen.i5.Thostkeyrepository25.checkWhereClause(Thostkeyrepository25.java:95)
	at com.gip.xyna.xnwh.persistence.memory.PreparedQueryForMemory.checkWhereClauseLocked(PreparedQueryForMemory.java:213)
	at com.gip.xyna.xnwh.persistence.memory.PreparedQueryForMemory.execute(PreparedQueryForMemory.java:469)
	at com.gip.xyna.xnwh.persistence.memory.PreparedQueryForMemory.execute(PreparedQueryForMemory.java:47)
	at com.gip.xyna.xnwh.persistence.memory.TableObject.getResultSet(TableObject.java:397)
	at com.gip.xyna.xnwh.persistence.memory.TableObject.query(TableObject.java:297)
	at com.gip.xyna.xnwh.persistence.memory.MemoryPersistenceLayerConnection.query(MemoryPersistenceLayerConnection.java:98)
	at com.gip.xyna.xnwh.persistence.memory.MemoryPersistenceLayerConnection.query(MemoryPersistenceLayerConnection.java:80)
	at com.gip.xyna.xnwh.persistence.ODSImpl$ODSConnectionImpl.lambda$query$3(ODSImpl.java:920)
	at com.gip.xyna.xnwh.persistence.ODSImpl$ODSConnectionImpl.executeConnectionCallHandleClosedConnection(ODSImpl.java:1336)
	at com.gip.xyna.xnwh.persistence.ODSImpl$ODSConnectionImpl.query(ODSImpl.java:920)
	at xact.ssh.HostKeyStorableRepository.queryDirectMatch(HostKeyStorableRepository.java:232)
	at xact.ssh.HostKeyStorableRepository.getDirectMatches(HostKeyStorableRepository.java:313)
	at xact.ssh.HostKeyStorableRepository.getHostKey(HostKeyStorableRepository.java:269)
	at xact.ssh.HostKeyStorableRepository.getHostKey(HostKeyStorableRepository.java:259)
	at xact.ssh.impl.SSHConnectionInstanceOperationImpl.evaluateHost(SSHConnectionInstanceOperationImpl.java:347)
	at xact.ssh.impl.SSHConnectionInstanceOperationImpl.createSession(SSHConnectionInstanceOperationImpl.java:286)
	at xact.ssh.impl.SSHConnectionInstanceOperationImpl.createSession(SSHConnectionInstanceOperationImpl.java:202)
	at xact.ssh.impl.SSHConnectionInstanceOperationImpl.connect(SSHConnectionInstanceOperationImpl.java:182)`

The underlying problem ist simple: There are too many jar files in server/lib. Especially the persistence layer jars are not supposed to be in there. That leads to the persistence layer classes not being loaded by some custom class loader that can resolve the storable classes. Instead it will be loaded by the app class loader.

As a workaround remove these jar files from server/lib.

This problem stems from the incomplete migration to maven.

=> Check all maven scripts to not include unnecessary jars.

**Comment by LukasFey-GIP** [comment]
removed libs from server/lib folder in #250 
removed libs inside module-applications in #259
