### ISSUE TITLE
Log4J 2.17.1 can't log Map with non String keys

### ISSUE THREAD

**Issue by csc-gip** [GIP-SmartMercial/xyna-factory#49]
https://github.com/GIP-SmartMercial/xyna-factory/blob/abb24e1f0bb4878b99426393d96e7ad7d033f381/modules/xact/dhcp/client/mdmimpl/DHCPv4ClientServiceImpl/src/xact/dhcp/client/impl/DHCPRequest.java#L232

leads to a ClassCastException. 

```
com.gip.xyna.xprc.xprcods.orderarchive.XynaExceptionInformationThrowable:
com.gip.xyna.xprc.exceptions.XPRC_UNEXPECTED_ERROR_PROCESS: unexpected
error executing order xact.dhcp.client.wf.Discover: ClassCastException
class xact.dhcp.client.DHCPUtils$DHCPFields cannot be cast to class
java.lang.String (xact.dhcp.client.DHCPUtils$DHCPFields is in unnamed
module of loader
com.gip.xyna.xfmg.xfctrl.classloading.SharedLibClassLoader @3fe0cae8;
java.lang.String is in module java.base of loader 'bootstrap')
    at
com.gip.xyna.xprc.xpce.execution.MasterWorkflowPostScheduler.addThrowableAsXynaException(MasterWorkflowPostScheduler.java:925)
    at
com.gip.xyna.xprc.xpce.execution.MasterWorkflowPostScheduler.executeAndCatchEverythingExceptSuspension(MasterWorkflowPostScheduler.java:514)
    at    ... (9 more)
    at ----- Caused by java.lang.ClassCastException class
xact.dhcp.client.DHCPUtils$DHCPFields cannot be cast to class
java.lang.String (xact.dhcp.client.DHCPUtils$DHCPFields is in unnamed
module of loader
com.gip.xyna.xfmg.xfctrl.classloading.SharedLibClassLoader @3fe0cae8;
java.lang.String is in module java.base of loader 'bootstrap'). (depth:
1)
    at
org.apache.logging.log4j.util.SortedArrayStringMap.<init>(SortedArrayStringMap.java:154)
    at
org.apache.logging.log4j.message.MapMessage.<init>(MapMessage.java:125)
    at org.apache.log4j.Category.maybeLog(Category.java:528)
    at org.apache.log4j.Category.info(Category.java:299)
    at xact.dhcp.client.impl.DHCPRequest.sendTo(DHCPRequest.java:231)
```

c.f.
https://logging.apache.org/log4j/2.x/manual/messages.html
looks like its fixed in 2.17.2 according to the tags
https://github.com/apache/logging-log4j2/commit/51da8e2a50a841bbe1aafe929e3ef29d2f3aa1f2#diff-98ade7200c7793e77d4ee2732864afdc250469b25fded714a82d5cf8ccba256a

**Comment by csc-gip** [comment]
Place to change version:
https://github.com/GIP-SmartMercial/xyna-factory/blob/bf23b4e7c11284766eda1625fd363f9088690f56/installation/build/pom.xml#L412-L431
