### ISSUE TITLE
Workflow Deployment Fails with "The object <wf> does not exist.

### ISSUE THREAD

**Issue by LukasFey-GIP** [GIP-SmartMercial/xyna-factory#6]
Deployment fails after creating a new workflow. Stacktrace:
`com.gip.xyna.xprc.exceptions.XPRC_XMOMObjectDoesNotExist: The object <wf> does not exist.
	at com.gip.xyna.xprc.xfractwfe.generation.GenerationBase$18.exec(GenerationBase.java:4321)
	at com.gip.xyna.xprc.xfractwfe.generation.GenerationBase.executeJobAndIncrementDeploymentState(GenerationBase.java:5232)
	at com.gip.xyna.xprc.xfractwfe.generation.GenerationBase.validate(GenerationBase.java:4316)
	at com.gip.xyna.xprc.xfractwfe.generation.GenerationBase.validateInCorrectOrder(GenerationBase.java:4310)
	at com.gip.xyna.xprc.xfractwfe.generation.GenerationBase.deploy(GenerationBase.java:2189)
	at com.gip.xyna.xprc.xfractwfe.generation.GenerationBase.deploy(GenerationBase.java:2800)
	at com.gip.xyna.xprc.xfractwfe.XynaFractalWorkflowEngine.deployWorkflow(XynaFractalWorkflowEngine.java:429)
	at com.gip.xyna.xmcp.XynaMultiChannelPortal.deployWF(XynaMultiChannelPortal.java:538)
	at com.gip.xyna.xact.filter.session.save.Persistence.deployWorkflow(Persistence.java:407)
	at com.gip.xyna.xact.filter.session.save.Persistence.deploy(Persistence.java:226)
	at com.gip.xyna.xact.filter.session.Modification.deploy(Modification.java:407)
	at com.gip.xyna.xact.filter.session.SessionBasedData.deploy(SessionBasedData.java:849)
	at com.gip.xyna.xact.filter.session.SessionBasedData.createXMOMGuiReply(SessionBasedData.java:338)
	at com.gip.xyna.xact.filter.session.SessionBasedData.processRequest(SessionBasedData.java:317)
	at com.gip.xyna.xact.filter.session.XMOMGui.processRequest(XMOMGui.java:107)
	at com.gip.xyna.xact.filter.XmomGuiAction.act(XmomGuiAction.java:139)
	at com.gip.xyna.xact.filter.XmomGuiAction.act(XmomGuiAction.java:90)
	at com.gip.xyna.xact.filter.RuntimeContextDependendAction.act(RuntimeContextDependendAction.java:75)
	at com.gip.xyna.xact.filter.H5XdevFilter.createXynaOrder(H5XdevFilter.java:428)
	at com.gip.xyna.xact.filter.H5XdevFilter.createXynaOrder(H5XdevFilter.java:71)
	at com.gip.xyna.xdev.xfractmod.xmdm.ConnectionFilter.createXynaOrder(ConnectionFilter.java:113)
	at com.gip.xyna.xdev.xfractmod.xmdm.EventListener.findResponsibleFilter(EventListener.java:443)
	at com.gip.xyna.xdev.xfractmod.xmdm.EventListener.processFilters(EventListener.java:339)
	at com.gip.xyna.xprc.xpce.FilterProcessingRunnable.run(FilterProcessingRunnable.java:53)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by LukasFey-GIP** [comment]
Identified cause: Expected path of workflow file was missing the file extension (.xml).
